# Generated by Django 5.2.12 on 2026-07-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auctionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='exclude_past_winners',
            field=models.BooleanField(default=True, help_text='If checked, users who already won a raffle in this event cannot win again'),
        ),
    ]
