# Generated by Django 5.2.12 on 2026-07-29 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_exclude_past_winners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventviewer',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='eventmessage',
            index=models.Index(fields=['event', 'created_at'], name='events_even_event_i_95aa65_idx'),
        ),
    ]
