# Generated by Django 5.2.12 on 2026-10-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auctionitem_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='points_award',
            field=models.PositiveIntegerField(default=0, help_text='Loyalty points credited to EACH winner automatically on draw (0 = physical prize, manual fulfillment)'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winner_policy',
            field=models.CharField(choices=[('inherit', 'Event default'), ('exclude', 'Exclude past winners'), ('allow', 'Everyone can win')], default='inherit', help_text="Per-raffle override of the event's exclude_past_winners flag (can still be changed while the raffle is pending)", max_length=10),
        ),
    ]
