# Generated by Django 5.2.12 on 2026-10-03 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_raffle_points_award_raffle_winner_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='brewery',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='fulfillment_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='fulfillment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('draft_created', 'Draft order created'), ('added_to_order', 'Added to order'), ('invoice_sent', 'Invoice sent'), ('fulfilled', 'Fulfilled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='min_increment',
            field=models.PositiveIntegerField(default=5, help_text='Minimum euros above the current bid'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='shopify_order_gid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='shopify_product_gid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='shopify_variant_gid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='size',
            field=models.CharField(blank=True, help_text='e.g. 75cl', max_length=50),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='untappd_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='excluded_users',
            field=models.ManyToManyField(blank=True, help_text='Members who can never win in this event (e.g. the staff presenting the stream). They still count as viewers.', related_name='excluded_from_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='raffle',
            name='fulfillment_type',
            field=models.CharField(choices=[('manual', 'Manual (WhatsApp/pickup)'), ('shopify', 'Shopify product on order'), ('points', 'Loyalty points')], default='manual', help_text='How winners receive this prize', max_length=10),
        ),
        migrations.AddField(
            model_name='raffle',
            name='shopify_product_gid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='raffle',
            name='shopify_variant_gid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winner_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="What the winner pays for the prize (empty/0 = free). Only meaningful for Shopify fulfillment, e.g. 'won for €100, normally €200'.", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='rafflewinner',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rafflewinner',
            name='fulfillment_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rafflewinner',
            name='fulfillment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('draft_created', 'Draft order created'), ('added_to_order', 'Added to order'), ('invoice_sent', 'Invoice sent'), ('fulfilled', 'Fulfilled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='rafflewinner',
            name='shopify_order_gid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='events.auctionitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-amount', 'created_at', 'id'],
                'indexes': [models.Index(fields=['item', 'amount'], name='events_bid_item_id_0c8787_idx')],
            },
        ),
    ]
