# Generated by Django 5.2.12 on 2026-10-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_raffle_fulfillment_type_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reactions_rev',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
