# Generated by Django 5.2.12 on 2026-07-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='email_policy',
            field=models.CharField(blank=True, choices=[('always', 'Always email'), ('fallback', 'Email only if push failed'), ('never', 'Never email')], help_text='Overrides the default email policy for this kind. Blank = use the kind default.', max_length=20),
        ),
    ]
