# Generated by Django 5.2.12 on 2026-07-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationdelivery_email_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationKindSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('birthday_gift', 'Birthday gift'), ('announcement', 'Announcement'), ('recommendations', 'Beer recommendations'), ('transactional', 'Transactional (orders, rewards)')], max_length=50, unique=True)),
                ('send_push', models.BooleanField(default=True, help_text='Send a push notification for this kind.')),
                ('send_email', models.BooleanField(default=True, help_text='Send an email for this kind. Untick to never email - push only.')),
                ('email_only_if_push_failed', models.BooleanField(default=True, help_text='Ticked: email is a fallback, sent only when the push could not be delivered (nobody gets both). Unticked: the email is always sent alongside the push - right for things worth keeping, like a discount code. Ignored when "Send email" is off.', verbose_name='Only email when push did not get through')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification delivery setting',
                'verbose_name_plural': 'Notification delivery settings',
                'ordering': ['kind'],
            },
        ),
    ]
