# Generated by Django 5.2.12 on 2026-07-29 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_seed_kind_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The notification heading. Keep it short - phones truncate.', max_length=120)),
                ('body', models.TextField(help_text='The message itself.', max_length=500)),
                ('url', models.CharField(blank=True, default='/', help_text='Where tapping the notification opens, e.g. /loyalty. Defaults to the home screen.', max_length=300)),
                ('kind', models.CharField(choices=[('birthday_gift', 'Birthday gift'), ('announcement', 'Announcement'), ('recommendations', 'Beer recommendations'), ('transactional', 'Transactional (orders, rewards)')], default='announcement', help_text='Decides whether an email follows the push - see Notification delivery settings.', max_length=50)),
                ('audience', models.CharField(choices=[('all', 'Everyone'), ('selected', 'Only the users I pick below'), ('push_only', 'Only users who can receive push')], default='all', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Leave empty to send immediately when you tick "Send now". Set a time to have it go out then instead.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft - not sent'), ('scheduled', 'Scheduled'), ('sending', 'Sending...'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('send_now', models.BooleanField(default=False, help_text='Tick and save to queue this message. Leave unticked to keep editing it as a draft.', verbose_name='Send now')),
                ('recipient_count', models.IntegerField(default=0)),
                ('push_sent_count', models.IntegerField(default=0)),
                ('email_sent_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(blank=True, help_text='Only used when the audience is "Only the users I pick below".', related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push message',
                'verbose_name_plural': 'Push messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
