# Generated by Django 5.2.12 on 2026-08-05, then edited to add the data
# migration that moves existing rows to the new defaults.
"""Make email opt-in: push stays on by default, email defaults to off.

Why the data migration flips only some rows
-------------------------------------------
The old defaults were push_enabled=True, email_enabled=True; the new defaults
are push_enabled=True, email_enabled=False. Rows still sitting on the old
*channel* default combination (push on, email on) are flipped to the new one
(email off), because:

- The mobile app has never exposed an email toggle, so email_enabled=True on
  an existing row can only be the old default - it is never a choice the user
  made themselves.
- Rows where push_enabled=False are left untouched: turning push off IS an
  explicit choice, and for those users email is the only channel they have
  left. Silently removing it would cut them off entirely.
- The per-category fields (birthday/announcements/recommendations) are
  deliberately ignored when matching: they are independent of the channel
  choice, so a user who only toggled a category still gets moved to the new
  email default, and their category choices are preserved as-is.

The reverse operation is a no-op: once flipped we can no longer tell which
rows used to be on the old default, so un-applying must not invent data.
"""

from django.db import migrations, models


def flip_old_default_rows(apps, schema_editor):
    """Flip rows still matching the old channel defaults to the new defaults.

    Old default: push_enabled=True, email_enabled=True.
    New default: push_enabled=True, email_enabled=False.

    Any row that differs from the old channel defaults (i.e. push_enabled is
    False) represents an explicit user choice and is left untouched. See the
    module docstring for the full reasoning.
    """
    NotificationPreference = apps.get_model('notifications', 'NotificationPreference')
    NotificationPreference.objects.filter(
        push_enabled=True, email_enabled=True,
    ).update(email_enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_broadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(flip_old_default_rows, migrations.RunPython.noop),
    ]
