# Generated by Django 5.2.12 on 2026-09-18 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Sluitingsdag',
                'verbose_name_plural': 'Sluitingsdagen',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PickupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Maandag'), (1, 'Dinsdag'), (2, 'Woensdag'), (3, 'Donderdag'), (4, 'Vrijdag'), (5, 'Zaterdag'), (6, 'Zondag')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Afhaaldag',
                'verbose_name_plural': 'Afhaaldagen',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='PickupRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Aangemeld'), ('cancelled', 'Geannuleerd')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Afhaal-aanmelding',
                'verbose_name_plural': 'Afhaal-aanmeldingen',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PickupActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('rsvp', 'Aangemeld'), ('cancel', 'Geannuleerd')], max_length=10)),
                ('pickup_date', models.DateField()),
                ('sync_status', models.CharField(choices=[('pending', 'In afwachting'), ('success', 'Gelukt'), ('failed', 'Mislukt'), ('skipped', 'Overgeslagen')], default='pending', max_length=10)),
                ('sync_attempts', models.IntegerField(default=0)),
                ('sync_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_action_logs', to=settings.AUTH_USER_MODEL)),
                ('rsvp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='fulfillment.pickuprsvp')),
            ],
            options={
                'verbose_name': 'Afhaal-actielog',
                'verbose_name_plural': 'Afhaal-actielogs',
                'ordering': ['-created_at'],
            },
        ),
    ]
