# Generated by Django 5.2.12 on 2026-05-30 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('register', 'Registration'), ('recommendations', 'View Recommendations'), ('taste_profile', 'View Taste Profile'), ('favorite_add', 'Add Favorite'), ('favorite_remove', 'Remove Favorite'), ('reward_redeem', 'Redeem Reward'), ('points_sync', 'Sync Points'), ('orders_view', 'View Orders'), ('untappd_link', 'Link Untappd'), ('untappd_unlink', 'Unlink Untappd'), ('cart_link', 'Generate Cart Link'), ('notification_dismiss', 'Dismiss Notification')], db_index=True, max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DashboardProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('analytics.usageevent',),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='analytics_u_event_t_0bb6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_u_user_id_909cb4_idx'),
        ),
    ]
