# Generated by Django 5.2.12 on 2026-08-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_usageevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usageevent',
            name='event_type',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'Registration'), ('recommendations', 'View Recommendations'), ('taste_profile', 'View Taste Profile'), ('favorite_add', 'Add Favorite'), ('favorite_remove', 'Remove Favorite'), ('reward_redeem', 'Redeem Reward'), ('points_sync', 'Sync Points'), ('orders_view', 'View Orders'), ('untappd_link', 'Link Untappd'), ('untappd_unlink', 'Unlink Untappd'), ('cart_link', 'Generate Cart Link'), ('random_beer', 'Random Beer Spin'), ('sixpack_generate', 'Sixpack Spin'), ('sixpack_checkout', 'Sixpack Checkout'), ('app_shop_view', 'View App Shop'), ('app_shop_checkout', 'App Shop Checkout'), ('screen_view', 'Screen View'), ('notification_dismiss', 'Dismiss Notification'), ('community_post', 'Create Post'), ('community_like', 'Like Post'), ('community_comment', 'Comment on Post'), ('community_message', 'Send Message'), ('community_profile_view', 'View Member Profile'), ('community_visibility_toggle', 'Toggle Community Visibility'), ('community_group_join', 'Join Group'), ('community_group_leave', 'Leave Group'), ('community_group_message', 'Group Message')], db_index=True, max_length=30),
        ),
    ]
