# Generated by Django 5.2.12 on 2026-03-24 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UntappdProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='untappd_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations_untappd_profile',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_id', models.CharField(max_length=50)),
                ('variant_id', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('product_url', models.URLField(blank=True, max_length=500)),
                ('untappd_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('abv', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('style', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_beers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations_favorite',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'beer_id')},
            },
        ),
    ]
