# Generated by Django 5.2.12 on 2026-05-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_favorite_untappd_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='untappd_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
