# Generated by Django 5.2.12 on 2026-08-06 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_favorite_untappd_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SixpackCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_hash', models.CharField(db_index=True, max_length=64)),
                ('items', models.JSONField()),
                ('pack_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charm_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_code', models.CharField(blank=True, max_length=32)),
                ('shopify_discount_id', models.CharField(blank=True, max_length=255)),
                ('cart_url', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sixpack_checkouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations_sixpack_checkout',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'pack_hash', 'created_at'], name='recommendat_user_id_6becaf_idx')],
            },
        ),
    ]
