# Generated by Django 5.2.12 on 2026-03-14 17:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('per_euro', 'Points per Euro spent'), ('per_order', 'Points per order'), ('product_sku', 'Points for specific product (by SKU)'), ('product_title', 'Points for product (by title contains)'), ('minimum_order', 'Bonus points for minimum order value'), ('first_order', 'Bonus points for first order')], max_length=50)),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('condition_value', models.CharField(blank=True, help_text='SKU, product title keyword, or minimum order amount', max_length=255)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='For per_euro: points per euro (e.g., 10 = 10 points per euro)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are evaluated first')),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Points Rule',
                'verbose_name_plural': 'Points Rules',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('reward_type', models.CharField(choices=[('fixed_discount', 'Fixed amount discount'), ('percentage_discount', 'Percentage discount'), ('free_shipping', 'Free shipping'), ('free_product', 'Free product')], max_length=50)),
                ('points_cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='For fixed_discount: amount in euros', max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='For percentage_discount: percentage (e.g., 10 for 10%)', max_digits=5, null=True)),
                ('product_sku', models.CharField(blank=True, help_text='For free_product: the SKU of the product', max_length=255)),
                ('shopify_discount_code', models.CharField(blank=True, help_text='Pre-created Shopify discount code to use', max_length=255)),
                ('create_shopify_discount', models.BooleanField(default=False, help_text='Automatically create a unique Shopify discount code when redeemed')),
                ('max_redemptions', models.IntegerField(blank=True, help_text='Maximum total redemptions (null = unlimited)', null=True)),
                ('max_per_customer', models.IntegerField(blank=True, help_text='Maximum redemptions per customer (null = unlimited)', null=True)),
                ('minimum_order_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order value to use this reward', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards',
                'ordering': ['points_cost'],
            },
        ),
        migrations.CreateModel(
            name='PointsBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('lifetime_earned', models.IntegerField(default=0)),
                ('lifetime_spent', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Points Balance',
                'verbose_name_plural': 'Points Balances',
            },
        ),
        migrations.CreateModel(
            name='ProcessedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_order_id', models.CharField(max_length=255, unique=True)),
                ('shopify_order_name', models.CharField(max_length=50)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('points_awarded', models.IntegerField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processed Order',
                'verbose_name_plural': 'Processed Orders',
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('discount_code', models.CharField(blank=True, max_length=255)),
                ('discount_code_used', models.BooleanField(default=False)),
                ('shopify_discount_id', models.CharField(blank=True, max_length=255)),
                ('shopify_order_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='loyalty.reward')),
            ],
            options={
                'verbose_name': 'Redemption',
                'verbose_name_plural': 'Redemptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', 'Points Earned'), ('spent', 'Points Spent'), ('adjusted', 'Manual Adjustment'), ('expired', 'Points Expired')], max_length=20)),
                ('points', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('shopify_order_id', models.CharField(blank=True, max_length=255)),
                ('shopify_order_name', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='loyalty.pointsrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='loyalty.reward')),
            ],
            options={
                'verbose_name': 'Points Transaction',
                'verbose_name_plural': 'Points Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
