# Generated by Django 5.2.12 on 2026-03-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='product_sku',
            new_name='shopify_product_id',
        ),
        migrations.AlterField(
            model_name='reward',
            name='shopify_product_id',
            field=models.CharField(blank=True, help_text='For free_product: Shopify product GID (e.g., gid://shopify/Product/123456)', max_length=255),
        ),
    ]
