# Generated by Django 5.2.12 on 2026-03-15 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_rename_product_sku_to_shopify_product_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('announcement', 'Announcement'), ('promotion', 'Promotion'), ('event', 'Event'), ('news', 'News')], default='announcement', max_length=20)),
                ('link_url', models.URLField(blank=True, help_text='Optional link to open when tapped')),
                ('link_text', models.CharField(blank=True, help_text="Button text (e.g., 'View Products')", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('show_from', models.DateTimeField(blank=True, help_text='Leave empty to show immediately', null=True)),
                ('show_until', models.DateTimeField(blank=True, help_text='Leave empty to show indefinitely', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='loyalty.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Read',
                'verbose_name_plural': 'Notifications Read',
                'unique_together': {('user', 'notification')},
            },
        ),
    ]
