# Generated by Django 5.2.12 on 2026-07-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_add_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsrule',
            name='only_after_registration',
            field=models.BooleanField(default=False, help_text='Only award points for orders placed after the user registered in the app'),
        ),
    ]
