# Generated by Django 5.2.12 on 2026-07-22 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_add_only_after_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_successful_sync', models.DateTimeField(blank=True, help_text='Used as created_at_min for partial sync', null=True)),
                ('last_shopify_order_id', models.CharField(blank=True, help_text='Highest Shopify order ID seen', max_length=255)),
                ('sync_status', models.CharField(choices=[('idle', 'Idle'), ('in_progress', 'In Progress'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('sync_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync State',
                'verbose_name_plural': 'Sync States',
            },
        ),
    ]
