# Generated by Django 5.2.12 on 2026-07-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_add_sync_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='image_url',
            field=models.URLField(blank=True, help_text='Product image URL. Auto-fetched from Shopify when saving with a product ID.'),
        ),
    ]
