# Generated by Django 5.2.12 on 2026-07-24 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0006_add_reward_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ordering', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reward Category',
                'verbose_name_plural': 'Reward Categories',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.AddField(
            model_name='reward',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Group this reward under a category. Leave empty for uncategorized.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='loyalty.rewardcategory'),
        ),
    ]
