# Generated by Django 5.2.12 on 2026-07-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0007_add_reward_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reward',
            options={'ordering': ['ordering', 'points_cost'], 'verbose_name': 'Reward', 'verbose_name_plural': 'Rewards'},
        ),
        migrations.AddField(
            model_name='reward',
            name='ordering',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first within a category'),
        ),
    ]
