# Generated by Django 5.2.12 on 2026-07-29 13:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0008_add_reward_ordering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayRewardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Turn the whole birthday reward feature on or off')),
                ('discount_type', models.CharField(choices=[('fixed_amount', 'Fixed amount off'), ('percentage', 'Percentage off')], default='fixed_amount', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Euros for fixed_amount, percent (e.g. 10 for 10%) for percentage', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('validity_days', models.PositiveIntegerField(default=30, help_text='How long the discount code stays valid', validators=[django.core.validators.MinValueValidator(1)])),
                ('lead_time_days', models.PositiveIntegerField(default=30, help_text='Anti-abuse: the birthdate must have been set at least this many days before the birthday for a gift to be issued')),
                ('minimum_age', models.PositiveIntegerField(default=18, help_text='Minimum age to receive a gift. Note: registration is always blocked below 18 regardless of this value.')),
                ('send_hour', models.PositiveIntegerField(default=9, help_text='Local hour (Europe/Amsterdam) at which gifts are sent', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Birthday Reward Config',
                'verbose_name_plural': 'Birthday Reward Config',
            },
        ),
        migrations.CreateModel(
            name='BirthdayReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Calendar year the birthday fell in')),
                ('discount_code', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_id', models.IntegerField(blank=True, help_text='notifications.NotificationDelivery id (not a FK, apps stay decoupled)', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Birthday Reward',
                'verbose_name_plural': 'Birthday Rewards',
                'ordering': ['-issued_at'],
                'unique_together': {('user', 'year')},
            },
        ),
    ]
