# Generated by Django 5.2.12 on 2026-08-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0009_birthdayrewardconfig_birthdayreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstransaction',
            name='breakdown',
            field=models.JSONField(blank=True, help_text='Per-rule breakdown of earned points: [{rule_id, rule_name, rule_type, points}]', null=True),
        ),
    ]
