# Generated by Django 5.2.12 on 2026-08-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0010_pointstransaction_breakdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdayrewardconfig',
            name='lead_time_days',
        ),
        migrations.RemoveField(
            model_name='birthdayrewardconfig',
            name='minimum_age',
        ),
    ]
