# Generated by Django 5.2.12 on 2026-08-21 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0011_remove_birthdayrewardconfig_lead_time_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('previewed', 'Previewed'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('action_type', models.CharField(choices=[('points', 'Points'), ('discount_code', 'Discount code'), ('raffle', 'Raffle entry')], max_length=20)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('product_matchers', models.JSONField(blank=True, default=list, help_text='[{"type": "sku"|"product_id"|"title"|"tag"|"collection", "value": "..."}]. Empty list = any product/order counts.')),
                ('min_distinct_products', models.PositiveIntegerField(default=1, help_text='Distinct matchers satisfied (the k-of-n case)')),
                ('min_total_quantity', models.PositiveIntegerField(default=1, help_text='Total matched item quantity across the window')),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, help_text='At least one qualifying order with total >= this', max_digits=10, null=True)),
                ('min_total_spend', models.DecimalField(blank=True, decimal_places=2, help_text='Cumulative paid-order spend inside the window >= this (all orders)', max_digits=10, null=True)),
                ('min_order_count', models.PositiveIntegerField(blank=True, help_text='Number of paid orders inside the window >= this', null=True)),
                ('first_order_only', models.BooleanField(default=False, help_text="User's first-ever order must fall inside the window")),
                ('only_after_registration', models.BooleanField(default=False, help_text='Only count orders placed after the user registered in the app')),
                ('requires_untappd', models.BooleanField(default=False, help_text='User has a linked Untappd profile')),
                ('min_points_balance', models.IntegerField(blank=True, help_text='Current points balance >= this at evaluation time', null=True)),
                ('registered_after', models.DateTimeField(blank=True, null=True)),
                ('resolved_product_ids', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('rule_sentence', models.TextField(blank=True, help_text='Plain-language NL summary shown to customers; auto-generated, editable')),
                ('points_amount', models.IntegerField(blank=True, null=True)),
                ('points_mode', models.CharField(choices=[('fixed', 'Fixed (once, on qualification)'), ('per_item', 'Per matched item')], default='fixed', max_length=10)),
                ('discount_type', models.CharField(blank=True, choices=[('fixed_amount', 'Fixed amount discount'), ('percentage', 'Percentage discount'), ('free_shipping', 'Free shipping'), ('free_product', 'Free product')], max_length=20)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_product_gid', models.CharField(blank=True, help_text='For free_product: Shopify product GID', max_length=255)),
                ('discount_validity_days', models.PositiveIntegerField(default=30)),
                ('notify_on_qualify', models.BooleanField(default=True)),
                ('qualify_title', models.CharField(blank=True, max_length=200)),
                ('qualify_body', models.TextField(blank=True, help_text='Blank = sensible NL default built from rule_sentence/prize')),
                ('preview_stale', models.BooleanField(default=True, help_text='Set on every condition-affecting save in draft/previewed; Studio requires a fresh preview to activate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, help_text='{"qualified_count", "users", "near_miss_count", "near_miss_users", "orders_scanned"}', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='loyalty.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Preview',
                'verbose_name_plural': 'Campaign Previews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRaffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_name', models.CharField(max_length=200)),
                ('prize_description', models.TextField(blank=True)),
                ('prize_image_url', models.URLField(blank=True)),
                ('num_winners', models.PositiveIntegerField(default=1)),
                ('draw_at', models.DateTimeField(blank=True, help_text='Null = manual draw only', null=True)),
                ('entry_mode', models.CharField(choices=[('single', '1 ticket'), ('per_order', '1 ticket per qualifying order'), ('per_item', '1 ticket per matched item')], default='single', max_length=10)),
                ('fulfillment_type', models.CharField(choices=[('shopify_code', 'Shopify discount code'), ('manual', 'Manual')], default='manual', help_text='shopify_code uses the campaign discount_* fields for the prize code', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('drawn', 'Drawn')], default='open', max_length=10)),
                ('drawn_at', models.DateTimeField(blank=True, null=True)),
                ('send_reminder', models.BooleanField(default=True, help_text='Reminder notification ~3h before draw_at')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raffle', to='loyalty.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Raffle',
                'verbose_name_plural': 'Campaign Raffles',
            },
        ),
        migrations.CreateModel(
            name='CampaignAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded', models.IntegerField(default=0, help_text='Cumulative for per_item mode')),
                ('discount_code', models.CharField(blank=True, max_length=255)),
                ('shopify_discount_id', models.CharField(blank=True, max_length=255)),
                ('notified_delivery_id', models.IntegerField(blank=True, help_text='notifications.NotificationDelivery id (not a FK, apps stay decoupled)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='loyalty.campaign')),
                ('points_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_awards', to='loyalty.pointstransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Award',
                'verbose_name_plural': 'Campaign Awards',
                'unique_together': {('campaign', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CampaignProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('qualified_at', models.DateTimeField(blank=True, help_text='Set once when thresholds are first met', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='loyalty.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Progress',
                'verbose_name_plural': 'Campaign Progress',
                'unique_together': {('campaign', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CampaignRaffleWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_code', models.CharField(blank=True, max_length=255)),
                ('shopify_discount_id', models.CharField(blank=True, max_length=255)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('fulfillment_status', models.CharField(choices=[('pending', 'Pending'), ('code_issued', 'Code issued'), ('manual_pending', 'Manual fulfillment pending'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_order_name', models.CharField(blank=True, max_length=50)),
                ('result_delivery_id', models.IntegerField(blank=True, help_text='notifications.NotificationDelivery id (not a FK, apps stay decoupled)', null=True)),
                ('drawn_at', models.DateTimeField(auto_now_add=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='loyalty.campaignraffle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_raffle_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Raffle Winner',
                'verbose_name_plural': 'Campaign Raffle Winners',
                'unique_together': {('raffle', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RaffleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_count', models.PositiveIntegerField(default=1)),
                ('matched_products', models.JSONField(blank=True, default=list, help_text='Display strings of what qualified them')),
                ('seen_at', models.DateTimeField(blank=True, help_text='Opened the raffle card', null=True)),
                ('result_seen_at', models.DateTimeField(blank=True, help_text='Watched the reveal', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='loyalty.campaignraffle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Raffle Entry',
                'verbose_name_plural': 'Raffle Entries',
                'unique_together': {('raffle', 'user')},
            },
        ),
    ]
