# Generated by Django 5.2.12 on 2026-08-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0012_campaign_campaignpreview_campaignraffle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='audience_filters',
            field=models.JSONField(blank=True, default=dict, help_text='{"min_age": 21, "birthday_month": 9, "min_app_age_days": 30, "min_lifetime_orders": 3, "active_within_days": 90} — all configured filters must match (AND). See services/audience.py.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='audience_mode',
            field=models.CharField(choices=[('orders', 'Purchase conditions'), ('audience', 'Selected audience (no purchase needed)')], default='orders', max_length=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='manual_user_ids',
            field=models.JSONField(blank=True, default=list, help_text='Hand-picked user ids, added to the filter matches (OR).'),
        ),
    ]
