# Generated by Django 5.2.12 on 2026-08-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0013_campaign_audience_filters_campaign_audience_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneStudio',
            fields=[
            ],
            options={
                'verbose_name': 'Campagne Studio',
                'verbose_name_plural': 'Campagne Studio',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('loyalty.campaign',),
        ),
    ]
