# Generated by Django 5.2.12 on 2026-08-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0014_campagnestudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='qualify_email_fallback',
            field=models.BooleanField(default=False, help_text='Email the qualify notification to members without an active push subscription (push-skip normally sends nothing at all). Off by default — be careful with email.'),
        ),
    ]
