# Generated by Django 5.2.12 on 2026-08-25 08:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0015_campaign_qualify_email_fallback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(default='hob', help_text='Which external system sent this grant', max_length=50)),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.CharField(help_text="Customer-facing NL text; rendered verbatim in the app's transaction history", max_length=255)),
                ('context', models.JSONField(blank=True, help_text='Caller-supplied context (sale id, chat message, ...) — audit only, never shown to the customer', null=True)),
                ('shopify_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending (no matching member yet)'), ('granted', 'Granted'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('notify', models.BooleanField(default=True, help_text='Send an in-app notification when the grant is fulfilled (also on a later claim)')),
                ('notified_delivery_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_grants', to='loyalty.pointstransaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Grant',
                'verbose_name_plural': 'Service Grants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'shopify_customer_id'], name='loyalty_ser_status_4a6d45_idx'), models.Index(fields=['status', 'email'], name='loyalty_ser_status_09dac2_idx')],
            },
        ),
    ]
