# Generated by Django 5.2.12 on 2026-08-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0016_servicegrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignaward',
            name='cart_url',
            field=models.TextField(blank=True, help_text='Storefront link that applies the code (and adds the free product to the cart); resolved once when the code is minted'),
        ),
        migrations.AddField(
            model_name='campaignrafflewinner',
            name='cart_url',
            field=models.TextField(blank=True, help_text='Storefront link that applies the prize code (and adds the prize product to the cart); resolved once at fulfillment'),
        ),
    ]
