# Generated by Django 5.2.12 on 2026-09-04 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0017_campaignaward_cart_url_campaignrafflewinner_cart_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignraffle',
            name='num_winners',
            field=models.PositiveIntegerField(default=1, help_text='Kept in sync with the summed prize quantities when the raffle has prize tiers'),
        ),
        migrations.CreateModel(
            name='CampaignRafflePrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of winners for this specific prize')),
                ('ordering', models.IntegerField(default=0, help_text='Draw order; prize 1 is handed out first')),
                ('discount_type', models.CharField(blank=True, choices=[('fixed_amount', 'Fixed amount discount'), ('percentage', 'Percentage discount'), ('free_shipping', 'Free shipping'), ('free_product', 'Free product')], help_text="Blank = use the campaign's discount config", max_length=20)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_product_gid', models.CharField(blank=True, help_text='For free_product: Shopify product GID of THIS prize', max_length=255)),
                ('discount_validity_days', models.PositiveIntegerField(blank=True, null=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='loyalty.campaignraffle')),
            ],
            options={
                'verbose_name': 'Campaign Raffle Prize',
                'verbose_name_plural': 'Campaign Raffle Prizes',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.AddField(
            model_name='campaignrafflewinner',
            name='prize',
            field=models.ForeignKey(blank=True, help_text="Which tier this winner got; null for a raffle without prize tiers (then the raffle's prize_name is the prize)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winners', to='loyalty.campaignraffleprize'),
        ),
    ]
