# Generated by Django 5.2.12 on 2026-09-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0018_alter_campaignraffle_num_winners_campaignraffleprize_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntenTool',
            fields=[
            ],
            options={
                'verbose_name': 'Puntentool',
                'verbose_name_plural': 'Puntentool',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('loyalty.pointstransaction',),
        ),
    ]
