# Generated by Django 5.2.12 on 2026-09-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0019_puntentool'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayreward',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('fixed_amount', 'Fixed amount off'), ('percentage', 'Percentage off')], max_length=20),
        ),
        migrations.AddField(
            model_name='birthdayreward',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
