# Generated by Django 5.2.12 on 2026-05-30 10:26

from django.db import migrations


def create_profiles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    CommunityProfile = apps.get_model('community', 'CommunityProfile')
    for user in User.objects.all():
        CommunityProfile.objects.get_or_create(user=user)


def reverse(apps, schema_editor):
    CommunityProfile = apps.get_model('community', 'CommunityProfile')
    CommunityProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_profiles, reverse),
    ]
