# Generated by Django 5.2.12 on 2026-07-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_suggestioncommentvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
