# Generated by Django 5.2.12 on 2026-10-03 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_post_edited_at_postcomment_edited_at_and_more'),
        ('events', '0008_event_reactions_rev'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('🍺', '🍺'), ('🔥', '🔥'), ('😂', '😂'), ('❤️', '❤️'), ('👍', '👍'), ('🤯', '🤯')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dm_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.message')),
                ('event_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='events.eventmessage')),
                ('group_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.groupmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dm_message', 'user', 'emoji'), name='uniq_dm_reaction'), models.UniqueConstraint(fields=('group_message', 'user', 'emoji'), name='uniq_group_reaction'), models.UniqueConstraint(fields=('event_message', 'user', 'emoji'), name='uniq_event_reaction'), models.CheckConstraint(condition=models.Q(models.Q(('dm_message__isnull', False), ('group_message__isnull', True), ('event_message__isnull', True)), models.Q(('dm_message__isnull', True), ('group_message__isnull', False), ('event_message__isnull', True)), models.Q(('dm_message__isnull', True), ('group_message__isnull', True), ('event_message__isnull', False)), _connector='OR'), name='reaction_exactly_one_message')],
            },
        ),
    ]
