from django.urls import path
from .views import (
    LoyaltySummaryView,
    PointsBalanceView,
    PointsTransactionsView,
    PointsRulesView,
    RewardsListView,
    RedeemRewardView,
    RedemptionsListView,
    SyncPointsView,
    SyncStatusView,
    NotificationsListView,
    NotificationDismissView,
    CampaignsListView,
    RafflesListView,
    RaffleSeenView,
    RaffleResultSeenView,
)

urlpatterns = [
    path("summary/", LoyaltySummaryView.as_view(), name="loyalty_summary"),
    path("balance/", PointsBalanceView.as_view(), name="points_balance"),
    path("transactions/", PointsTransactionsView.as_view(), name="points_transactions"),
    path("rules/", PointsRulesView.as_view(), name="points_rules"),
    path("rewards/", RewardsListView.as_view(), name="rewards_list"),
    path("redeem/", RedeemRewardView.as_view(), name="redeem_reward"),
    path("redemptions/", RedemptionsListView.as_view(), name="redemptions_list"),
    path("sync/", SyncPointsView.as_view(), name="sync_points"),
    path("sync/status/", SyncStatusView.as_view(), name="sync_status"),
    path("campaigns/", CampaignsListView.as_view(), name="campaigns_list"),
    path("raffles/", RafflesListView.as_view(), name="raffles_list"),
    path("raffles/<int:raffle_id>/seen/", RaffleSeenView.as_view(), name="raffle_seen"),
    path("raffles/<int:raffle_id>/result-seen/", RaffleResultSeenView.as_view(), name="raffle_result_seen"),
    path("notifications/", NotificationsListView.as_view(), name="notifications_list"),
    path("notifications/<int:notification_id>/dismiss/", NotificationDismissView.as_view(), name="notification_dismiss"),
]
