# Generated by Django 5.2.12 on 2026-07-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, help_text='Date of birth. Must be 18+. Locked once a birthday gift has been issued.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate_set_at',
            field=models.DateTimeField(blank=True, help_text='When the birthdate was last set. Used for the anti-abuse lead time.', null=True),
        ),
    ]
