# Generated by Django 5.2.12 on 2026-07-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birthdate_user_birthdate_set_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last recorded activity. Updated from analytics.tracker.track().', null=True),
        ),
    ]
