# Generated by Django 5.2.12 on 2026-08-15 09:39

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_lowercase_emails'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
