# Generated by Django 5.2.12 on 2026-09-04 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Normalized to UPPERCASE on save. Keep it short and unambiguous — people type this off a flyer.', max_length=64, unique=True)),
                ('label', models.CharField(help_text="What this code is for, e.g. 'Flyer Utrecht september'. Shown to the member in their points history.", max_length=200)),
                ('points', models.PositiveIntegerField(default=100, help_text='Welcome bonus awarded once, at registration.')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, help_text="Leave empty for 'valid immediately'.", null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text="Leave empty for 'never expires'.", null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited.', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Signup Code',
                'verbose_name_plural': 'Signup Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='signup_code_raw',
            field=models.CharField(blank=True, default='', help_text='The code as it arrived (QR or typed), valid or not.', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='welcome_bonus_awarded_at',
            field=models.DateTimeField(blank=True, help_text='When the signup-code welcome bonus was paid out. Set once, ever.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signups', to='users.signupcode'),
        ),
    ]
